name: Revenge
author: LilCrispy2o9/Angelo Vidrio
description: Have revenge 1v1 battles!
version: 1.0.0
main: Revenge\Main
api: [1.12.0]
commands:
    revenge:
        description: Main Revenge command
        permission: revenge.cmd
permissions:
    revenge:
        default: true
        description: "Main Revenge command"
        children:
            revenge.cmd:
                default: true
                description: "Main Revenge command"
